### PR TITLE
Fix CI build

### PR DESCRIPTION
**Pull request by epicfaace**
- Fix branch name so CI runs on PRs
- Fix PR build

### CODE REVIEW

**Review by hs4man21 — APPROVED** [review]
Lgtm!

**Review by sbcatania — APPROVED** [review]

**Comment by sbcatania** [comment]
@epicfaace seems like a check is failing here? should I not merge?

**Comment by epicfaace** [comment]
Yeah -- it doesn't actually fix the CI build problem. I get this cryptic error:

image


I've been stuck on this for a while (hence the commits) so this shouldn't be merged until it can be fixed.

**Comment by sbcatania** [comment]
@epicfaace good to merge now?

**Comment by epicfaace** [comment]
@sbcatania Yes! I half didn't expect this to fix it but glad it did 😁

**Pull request merged**
